services:

  backend:
    build: .
    container_name: cartbit-backend
    ports:
      - "5000:5000"
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: cartbit-redis
    ports:
      - "6379:6379"